### ISSUE TITLE
bug on the table

### ISSUE THREAD

**Issue by GabsGear** [pietrofxq/docker-complex#1]
Docker unlocks the potential of your organization by giving developers and IT the freedom to build, manage and secure business-critical applications without the fear of technology or infrastructure lock-in.
I copy this documentation part only for comer o cu de quem ta lendo!
:dancer:

**Comment by pietrofxq** [comment]
Solved by comendo o cu de quem criou a issue

**Comment by matheusfrancisco** [comment]
hahahahahahahahahahahhahahahaha passei e sai correndo..
